logtime ready to merge!

diff --git a/logtime b/logtime
--- a/logtime
+++ b/logtime
@@ -3,7 +3,17 @@
 config="$HOME/.config/logtime"
 test -d "$config" || mkdir -p "$config"
 USAGE="Usage: $(basename $0) [OPTIONS] b|e [MESSAGE]"
+log_check='calctime --check-status'
 
+check_status_vs() {
+    new_status="$1"
+    old_status="$($log_check "$outfile")"
+    test $? -eq 0 ||\
+      die $? "$0: couldn't check status - $log_check died with status $?"
+    test $new_status != $old_status
+    return $?
+}
+    
 die() {
     status="$1"
     shift
@@ -18,6 +28,10 @@ warn() {
 while [ $# -gt 1 ]; do
     case "$1" in
       -f)
+        force=1
+        shift 1
+        ;;
+      -o)
         outfile="$2"
         shift 2
         break
@@ -31,7 +45,7 @@ while [ $# -gt 1 ]; do
         shift 1
         ;;
       -*)
-        die 1 "flag $1 not recognized"
+        die 1 "$0: flag $1 not recognized"
         ;;
       *)
         break
@@ -44,6 +58,11 @@ test -n "$clock" || die 1 $USAGE
 if [ -z "$outfile" ]; then
     outfile="$config/$1"
     shift
+fi
+
+if test ! "$force"; then
+    check_status_vs "$clock" ||\
+      die $? "$0: trying to clock $clock with $outfile, already clocked $clock"
 fi
 
 test $# -gt 0 && comment='# '"$@"
